[magic-tiler-ide]
split = "horizontal"
children = ['linters', 'main', 'tests']
sizes = [20, 47, 33]

[linters]
split="vertical"
sizes = [50, 50]
children = ['formatting', 'typechecking']

[main]
split="vertical"
children = ['editors', 'gutter']
sizes = [80, 20]

[editors]
sizes = [50, 50]
children = ['left-editor', 'right-editor']
split = "horizontal"

[formatting]
command = "alacritty --working-directory ~/workspace/abstractlyZach/magic-tiler/ -e sh -c 'fd | entr sh -c \"make format && make lint\"; zsh'"
mark = "formatting"

[typechecking]
command = "alacritty --working-directory ~/workspace/abstractlyZach/magic-tiler/ -e sh -c 'fd | entr make typecheck'; zsh"
mark = "typechecking"

[left-editor]
command = "alacritty --working-directory ~/workspace/abstractlyZach/magic-tiler/ -e sh -c 'kak src/magic_tiler/magic_tiler.py'"
mark = "left-editor"

[right-editor]
command = "alacritty --working-directory ~/workspace/abstractlyZach/magic-tiler/ -e sh -c 'kak README.md'"
mark = "right-editor"

[gutter]
command = "alacritty --working-directory ~/workspace/abstractlyZach/magic-tiler/ -e sh -c 'neofetch; zsh'"
mark = "gutter"

[tests]
command = "alacritty --working-directory ~/workspace/abstractlyZach/magic-tiler/ -e sh -c 'fd | entr make test'; zsh"
mark = "tests"
